
var Options=function(){return{challengeKeyCounter:0,defaultChallengeText:"The procrastinator is often remarkably optimistic about his ability to complete a task on a tight deadline; this is usually accompanied by expressions of reassurance that everything is under control. (Therefore, there is no need to start.) Lulled by a false sense of security, time passes. At some point, he crosses over an imaginary starting time and suddenly realizes, \"Oh no! I am not in control! There isn't enough time!\"",init:function(){$('a.close').click(function(){window.open('','_self','');window.close();});this.initNav();this.initChallenge();this.initMaxTimeAllowed();this.initActiveDays();this.initActiveHours(true);this.initResetTime(true);this.initBlockedSites();this.initAllowedSites();this.initNuclearOption(true);this.initCustomizeInterface();this.initImportExport();},initNav:function(){$('#nav li').click(function(){var classes=$(this).attr('class');var classesArray=classes.split(' ');Options.selectNav(classesArray[0]);});if(window.location.hash){var hash=window.location.hash.replace('#','');hash=hash.replace('Tab','');this.selectNav(hash);}else{this.selectNav('maxTimeAllowed');}},selectNav:function(navItem){$('#nav li').removeClass('active');$('.option.active').hide();$('#body .'+navItem).show();$('.'+navItem).addClass('active');window.location.hash='#'+navItem+'Tab';},addToBlacklist:function(domain,id){var added=bg().ListManager.addToBlacklist(domain);if(added){$('#'+id).slideUp('fast');var html=this.addBlockedSiteToListHTML(domain,id);$('#blockedSitesList').append(html);if(bg().StayFocusd.isProductivityBypassActive()){$('.hideOnBypass').hide();}}},removeFromList:function(domain,id,listType){var removed=false;if(listType=='black'){if(bg().NuclearOption.isActive()&&bg().NuclearOption.getBlockType()=='blocked'){alert('You cannot remove Blocked Sites while the Nuclear Option is active.');return false;}
removed=bg().ListManager.removeFromBlacklist(domain);}else{removed=bg().ListManager.removeFromWhitelist(domain);}
if(removed){$('#'+id).slideUp('fast');}},initMaxTimeAllowed:function(){$("#maxTimeAllowed").keydown(function(event){Options.allowOnlyNumbers(event);});if(bg().StayFocusd.isMaxTimeAllowedExceeded()){$('#maxTimeAllowed').attr('disabled','disabled');$('#maxTimeAllowedButton').attr('disabled','disabled');$('#maxTimeAllowedMsg').html('Your time for today has expired. You cannot change these settings until tomorrow.');$('#maxTimeAllowedMsg').show();}},setMaxTimeAllowed:function(maxTimeAllowed){var success=bg().StayFocusd.setMaxTimeAllowed(maxTimeAllowed);if(success===false){$("#maxTimeAllowed").val(bg().StayFocusd.getMaxTimeAllowed());}},initActiveDays:function(){var activeDays=bg().StayFocusd.getActiveDays();var date=new Date();var todayDay=date.getDay();$('.activeDay').each(function(){var checkbox=$(this);var day=checkbox.val();if(activeDays.inArray(day)===true){checkbox.attr('checked','checked');}
if(day==todayDay){if(checkbox.attr('checked')){checkbox.attr('disabled','disabled');}
else{checkbox.click(function(){checkbox.attr('disabled','disabled');})}}});$('.activeDay').click(function(){Options.setActiveDays();});},setActiveDays:function(){var activeDays=[];var date=new Date();var todayDay=date.getDay();$('.activeDay:checked').each(function(){var day=parseInt($(this).val(),10);if(day==todayDay){$(this).attr('disabled','disabled');}
activeDays.push(day);});bg().StayFocusd.setActiveDays(activeDays);},initActiveHours:function(initClick){if(initClick===true){$('#setActiveHours').click(function(){Options.setActiveHours();});}
var activeHours=bg().StayFocusd.getActiveHours();var startTime=DateUtils.parseMilitaryTime(activeHours.startTime);var endTime=DateUtils.parseMilitaryTime(activeHours.endTime);$('.start .hour').val(startTime.hour).attr('selected','selected');$('.start .min').val(startTime.min).attr('selected','selected');$('.start .ampm').val(startTime.ampm).attr('selected','selected');$('.end .hour').val(endTime.hour).attr('selected','selected');$('.end .min').val(endTime.min).attr('selected','selected');$('.end .ampm').val(endTime.ampm).attr('selected','selected');var activeHoursQueue=bg().StayFocusd.getActiveHoursQueue();if(activeHoursQueue!=false){var timestamp=parseInt(activeHoursQueue.timestamp,10);startTime=activeHoursQueue.startTime;endTime=activeHoursQueue.endTime;var queueDate=new Date(timestamp);var queueMonth=queueDate.getMonth();var queueDay=queueDate.getDate();var queueYear=queueDate.getFullYear();var queueHour=queueDate.getHours();var queueMin=queueDate.getMinutes();var queueAmpm='AM';if(queueHour>=12){queueHour=queueHour-12;queueAmpm='PM';}
if(queueHour==0){queueHour=12;queueAmpm='AM';}
queueMin=DateUtils.toTwoDigits(queueMin);var months=['January','February','March','April','May','June','July','August','September','October','November','December'];var parsedStart=DateUtils.parseMilitaryTime(startTime);var parsedEnd=DateUtils.parseMilitaryTime(endTime);var queueString='Starting on '+months[queueMonth]+' '+queueDay+', '+queueYear+' at '+queueHour+':'+queueMin+' '+queueAmpm;queueString+=', your Active Hours will be from '+parsedStart.display+' to '+parsedEnd.display+'</small>';$('#activeHoursMsg').html(queueString);$('#activeHoursMsg').show();}},setActiveHours:function(){var months=['January','February','March','April','May','June','July','August','September','October','November','December'];var todayDate=new Date();var todayMonth=todayDate.getMonth();var todayDay=todayDate.getDate();var todayYear=todayDate.getFullYear();todayDay=DateUtils.toTwoDigits(todayDay);var todayString=months[todayMonth]+' '+todayDay+', '+todayYear;var startHour=$('.start .hour').val();var startMin=$('.start .min').val();var startAmpm=$('.start .ampm').val();var startDisplayHour=(startHour==0)?12:startHour;if(startAmpm=='pm'){startHour=parseInt(startHour,10)+12;}
var startTime=startHour+':'+startMin;var startDate=new Date(todayString+' '+startTime+':00');var startTimestamp=startDate.getTime();var endHour=$('.end .hour').val();var endMin=$('.end .min').val();var endAmpm=$('.end .ampm').val();var endDisplayHour=(endHour==0)?12:endHour;if(endAmpm=='pm'){endHour=parseInt(endHour,10)+12;}
var endTime=endHour+':'+endMin;var endDate=new Date(todayString+' '+endTime+':00');var endTimestamp=endDate.getTime();var confirmed=true;if(endTimestamp<=startTimestamp){var startString=startDisplayHour+':'+startMin+' '+startAmpm.toUpperCase();var endString=endDisplayHour+':'+endMin+' '+endAmpm.toUpperCase();confirmed=confirm('StayFocusd will be active between '+startString+' and midnight, and then between midnight and '+endString+'.\n\nAre you sure that\'s what you meant to do?');}
if(confirmed){bg().StayFocusd.setActiveHoursQueue(startTime,endTime);if(bg().StayFocusd.isFirstInstallAllowanceActive()===false){alert("Your active hours have been set. \n\nIMPORTANT: These changes will not go into effect until this time tomorrow (24 hours from now).");}else{alert("Your active hours have been set.");}}
this.initActiveHours();},initResetTime:function(initClick){if(initClick===true){$('#setResetTime').click(function(){Options.setResetTime();});}
var resetTime=bg().StayFocusd.getResetTime();var parsedTime=DateUtils.parseMilitaryTime(resetTime);$('.reset .hour').val(parsedTime.hour).attr('selected','selected');$('.reset .min').val(parsedTime.min).attr('selected','selected');$('.reset .ampm').val(parsedTime.ampm).attr('selected','selected');var resetTimeQueue=bg().StayFocusd.getResetTimeQueue();if(resetTimeQueue!=false){var timestamp=parseInt(resetTimeQueue.timestamp,10);resetTime=resetTimeQueue.resetTime;var queueDate=new Date(timestamp);var queueMonth=queueDate.getMonth();var queueDay=queueDate.getDate();var queueYear=queueDate.getFullYear();var queueHour=queueDate.getHours();var queueMin=queueDate.getMinutes();var queueAmpm='AM';if(queueHour>=12){queueHour=queueHour-12;queueAmpm='PM';}
if(queueHour==0){queueHour=12;queueAmpm='AM';}
queueMin=DateUtils.toTwoDigits(queueMin);var months=['January','February','March','April','May','June','July','August','September','October','November','December'];parsedTime=DateUtils.parseMilitaryTime(resetTime);var queueString='Starting on '+months[queueMonth]+' '+queueDay+', '+queueYear+' at '+queueHour+':'+queueMin+' '+queueAmpm;queueString+=', your Daily Reset Time will be '+parsedTime.display+'.</small>';$('#resetTimeMsg').html(queueString);$('#resetTimeMsg').show();}},setResetTime:function(){var resetHour=$('.reset .hour').val();var resetMin=$('.reset .min').val();var resetAmpm=$('.reset .ampm').val();if(resetAmpm=='pm'){resetHour=parseInt(resetHour,10)+12;}
var resetTime=resetHour+':'+resetMin;bg().StayFocusd.setResetTimeQueue(resetTime);if(bg().StayFocusd.isFirstInstallAllowanceActive()===false){alert("Your daily reset time has been set. \n\nIMPORTANT: This change will not go into effect until this time tomorrow (24 hours from now).");}else{alert("Your daily reset time has been set.");}
this.initResetTime();},initBlockedSites:function(){this.createBlockedSitesListHTML();if(bg().StayFocusd.isMaxTimeAllowedExceeded()){$('#blockedSitesMsg').html('Your time for today has expired. You cannot remove Blocked Sites until after your Daily Reset Time has passed. (You can still add them though.)');$('#blockedSitesMsg').show();}
$('input[name=addBlockedSites]').click(function(){Options.addBlockedSites();});$('input[name=reddiggliciousOption]').click(function(){Options.toggleOutgoingLinksOption();});$('#showSuggestedSitesList').click(function(){Options.getSuggestedSitesList();});if(bg().StayFocusd.isOutgoingLinksOptionActive()){$('input[name=reddiggliciousOption]').attr('checked','checked');if(bg().StayFocusd.isMaxTimeAllowedExceeded()){$('input[name=reddiggliciousOption]').attr('disabled','disabled');}}},toggleOutgoingLinksOption:function(){if(bg().StayFocusd.isOutgoingLinksOptionActive()){bg().StayFocusd.setLocal('countdownForOutgoingLinks','false');}else{bg().StayFocusd.setLocal('countdownForOutgoingLinks','true');}},getSuggestedSitesList:function(){$.ajax({type:'GET',url:bg().StayFocusd.apiURL+'/SiteList/suggestions/black.json',data:null,success:function(response){var parsedResponse=JSON.parse(response);if(parsedResponse.count===0||parsedResponse.data==undefined){alert('Error loading suggested sites list. Please email support@stayfocusd.com and let me know if you get this error.');return false;}
Options.addSuggestedSitesToList(parsedResponse.data);},error:function(response){alert('Error loading suggested sites list. Please email support@stayfocusd.com and let me know if you get this error.');return false;}});},addSuggestedSitesToList:function(siteList){var items=[];for(name in siteList){var domain=siteList[name];if(bg().ListManager.isBlacklisted(domain)){continue;}
var id=name.split(' ').join('-').toLowerCase();var item='<li id="'+id+'"><img src="img/add_10x10.png" onclick="Options.addToBlacklist(\''+domain+'\',\''+id+'\',\'black\');" title="Add '+name+' to the Blocked Sites list" alt="Add"> '+name+'</li>';items.push(item);}
$('#suggestedSitesList').html(items.join("\n"));$('#suggestedSites').slideToggle();},addBlockedSites:function(){var newBlockedSites=$('#newBlockedSites').val();if(newBlockedSites!==''){var newBlockedSitesArray=newBlockedSites.split("\n");for(var i=0;i<newBlockedSitesArray.length;i++){var domain=newBlockedSitesArray[i];if(domain.length==0){continue;}
bg().ListManager.addToBlacklist(domain);}
this.createBlockedSitesListHTML();this.createAllowedSitesListHTML();$('#newBlockedSites').val('');}},createBlockedSitesListHTML:function(){var blacklist=bg().ListManager.getBlacklistedDomains();var html='';if(blacklist.length===0){html+='<li><i>No sites yet</i></li>';}else{for(var i=0;i<blacklist.length;i++){html+=this.addBlockedSiteToListHTML(blacklist[i],'blacklist-'+i);}}
$('#blockedSitesList').html(html);if(bg().StayFocusd.isProductivityBypassActive()){$('.hideOnBypass').hide();}},addBlockedSiteToListHTML:function(domain,id){var html='';html+='<li id="'+id+'" class="domain">';html+='<img src="img/remove_10x10.png" class="hideOnBypass" onclick="Options.removeFromList(\''+domain+'\',\''+id+'\',\'black\');" title="Remove '+domain+' from the Blocked Sites list" alt="Remove">';html+=domain;html+='</li>';return html;},initAllowedSites:function(){if(bg().NuclearOption.isActive()){$('#newAllowedSites').val('You cannot add Allowed Sites while the Nuclear Option is active');$('#newAllowedSites').attr('disabled','disabled');$('#newAllowedSites').addClass('disabled');$('input[name=addAllowedSites]').attr('disabled','disabled');}else{$('#newAllowedSites').val('');$('#newAllowedSites').attr('disabled','');$('#newAllowedSites').removeClass('disabled');$('input[name=addAllowedSites]').attr('disabled','');$('input[name=addAllowedSites]').click(function(){Options.addAllowedSites();});}
this.createAllowedSitesListHTML();},addAllowedSites:function(){var newAllowedSites=$('#newAllowedSites').val();if(newAllowedSites!==''){var newAllowedSitesArray=newAllowedSites.split("\n");for(var i=0;i<newAllowedSitesArray.length;i++){var domain=newAllowedSitesArray[i];if(domain.length==0){continue;}
bg().ListManager.addToWhitelist(domain);}
this.createBlockedSitesListHTML();this.createAllowedSitesListHTML();$('#newAllowedSites').val('');}},createAllowedSitesListHTML:function(){var whitelist=bg().ListManager.getWhitelistedDomains();var html='';if(whitelist.length===0){html+='<li><i>No sites yet</i></li>';}else{for(var i=0;i<whitelist.length;i++){html+='<li id="whitelist-'+i+'" class="domain">';html+='<img src="img/remove_10x10.png" onclick="Options.removeFromList(\''+whitelist[i]+'\',\'whitelist-'+i+'\',\'white\');" title="Remove '+whitelist[i]+' from the Blocked Sites list" alt="Remove">'+whitelist[i];html+='</li>';}}
$('#allowedSitesList').html(html);},setNuclearOption:function(){if($('#nuclearOptionForm input[name=blockLength]').val()=='0'){alert('The minimum time setting for the Nuclear Option is 1 hour.');return false;}
var confirmed=confirm(this.getNuclearOptionConfirmationMsg());if(confirmed){var settings={};settings.blockType=$('#nuclearOptionForm input[name=blockType]:checked').val();settings.contentType=$('#nuclearOptionForm input[name=contentType]:checked').val();settings.smartBomb={multimedia:$('#nuclearOptionForm input[name=multimedia]').attr('checked'),forms:$('#nuclearOptionForm input[name=forms]').attr('checked'),logins:$('#nuclearOptionForm input[name=logins]').attr('checked'),images:$('#nuclearOptionForm input[name=images]').attr('checked')};settings.blockLength=parseFloat($('#nuclearOptionForm input[name=blockLength]').val());settings.startType=$('#nuclearOptionForm input[name=startType]:checked').val();settings.frequency=$('#nuclearOptionForm input[name=frequency]:checked').val();settings.startHour=null;settings.startMin=null;settings.startAmPm=null;if(settings.startType=='atScheduledTime'){settings.startHour=$('#nuclearOptionForm select[name=startHour]').val();settings.startMin=$('#nuclearOptionForm select[name=startMin]').val();settings.startAmPm=$('#nuclearOptionForm select[name=startAmPm]').val();}
bg().NuclearOption.saveSettings(settings);if(settings.startType=='now'){bg().NuclearOption.activate();}
this.initNuclearOption();this.initAllowedSites();alert('Commencing Nuclear Option. May God have mercy on your soul.');}},getNuclearOptionConfirmationMsg:function(){var startHour=$('#nuclearOptionForm select[name=startHour]').val();var startMin=$('#nuclearOptionForm select[name=startMin]').val();var startAmPm=$('#nuclearOptionForm select[name=startAmPm]').val();var contentType=$('#nuclearOptionForm input[name=contentType]:checked').val();var confirmMsg="StayFocusd will block ";if(contentType=='smartBomb'){var multimedia=$('#nuclearOptionForm input[name=multimedia]').attr('checked');var forms=$('#nuclearOptionForm input[name=forms]').attr('checked');var images=$('#nuclearOptionForm input[name=images]').attr('checked');var logins=$('#nuclearOptionForm input[name=logins]').attr('checked');var contentTypes=[];if(multimedia){contentTypes.push('multimedia');}
if(forms){contentTypes.push('forms');}
if(logins){contentTypes.push('logins');}
if(images){contentTypes.push('images');}
confirmMsg+=contentTypes.join('/')+' for ';}
confirmMsg+=$('#nuclearOptionForm input[name=blockType]:checked + label').text();confirmMsg+=" for "+$('#nuclearOptionForm input[name=blockLength]').val()+" hour(s)";confirmMsg+=" starting ";var startType=$('#nuclearOptionForm input[name=startType]:checked').val();switch(startType){case'now':confirmMsg+="right now";break;case'whenMaxTimeAllowedExceeded':confirmMsg+="when my Max Time Allowed has been exceeded";break;case'atScheduledTime':confirmMsg+="at ";confirmMsg+=(startHour=='00')?'12':startHour;confirmMsg+=":"+startMin;confirmMsg+=" "+startAmPm.toUpperCase();}
var frequency=$('#nuclearOptionForm input[name=frequency]:checked').val();var day=new Date().getDay();var isActiveNow=frequency!='everyWeekday'||(day>0&&day<6);if(startType=='now'){confirmMsg+="."}else{confirmMsg+=(isActiveNow)?" today.":" on Monday.";}
if(startType=='atScheduledTime'&&DateUtils.hasTimePassed(startHour,startMin,startAmPm)&&isActiveNow){confirmMsg+="\n\nYour selected time has already passed, so the Nuclear Option will go into effect immediately.";}else if(startType=='whenMaxTimeAllowedExceeded'&&bg().StayFocusd.isMaxTimeAllowedExceeded()){confirmMsg+="\n\nYour Max Time Allowed for today has already been exceeded, so the Nuclear Option will go into effect immediately.";}
confirmMsg+="\n\nAre you sure you want to do this?";return confirmMsg;},getNuclearOptionExpirationDate:function(){var expires=bg().NuclearOption.getExpiration();var dateObj=DateUtils.timestampToDisplayDate(expires);return dateObj.month+'/'+dateObj.day+'/'+dateObj.year+' at '+dateObj.hours+':'+dateObj.minutes+' '+dateObj.ampm;},initNuclearOption:function(initClick){if(initClick===true){$('#activateNuclearOptionButton').click(function(){Options.setNuclearOption();});$("#nuclearOptionForm input[name=blockLength]").keydown(function(event){Options.allowOnlyNumbers(event,true);});$('#nuclearOptionForm input[name=startType]').click(function(){if($(this).val()=='atScheduledTime'){$('#nuclearOptionScheduledTime').show();}else{$('#nuclearOptionScheduledTime').hide();}
if($(this).val()=='now'){$('#nuclearOptionFrequency').hide();}else{$('#nuclearOptionFrequency').show();}});$('#nuclearOptionForm input[name=contentType]').click(function(){if($(this).val()=='smartBomb'){$('#smartBombOptions').show();}else{$('#smartBombOptions').hide();}});}
this.setNuclearOptionDefaults();if(bg().NuclearOption.isActive()){this.restrictNuclearOptionSettings();var expiration=bg().NuclearOption.getExpiration();expiration=DateUtils.timestampToDisplayDate(expiration);var displayDate=expiration.hours+":"+expiration.minutes+" "+expiration.ampm+" on "+expiration.month+"/"+expiration.day+"/"+expiration.year;$('#nuclearOptionMsg').html('The Nuclear Option is active until '+displayDate+".");$('#nuclearOptionMsg').show();}},restrictNuclearOptionSettings:function(){this.disallowMoreLenientNuclearOption('blockType','all','allExceptAllowed','blocked');this.disallowMoreLenientNuclearOption('contentType','wholeSite','smartBomb',null);this.disallowMoreLenientNuclearOption('startType','now','whenMaxTimeAllowedExceeded','atScheduledTime');this.disallowMoreLenientNuclearOption('frequency','everyDay','everyWeekday','todayOnly');$('#nuclearOptionForm input[name=blockLength]').change(function(){var currentBlockLength=bg().NuclearOption.settings.blockLength;if(currentBlockLength!==undefined&&$(this).val()<currentBlockLength){alert("You cannot choose a more lenient setting for the Nuclear Option while it is active.");$(this).val(currentBlockLength);return false;}});if($('#nuclearOptionForm input[value=atScheduledTime]').attr('checked')){$('#nuclearOptionScheduledTime select').attr('disabled','disabled');}},disallowMoreLenientNuclearOption:function(inputName,high,medium,low){var alertFunction=function(){alert("You cannot choose a more lenient setting for the Nuclear Option while it is active.");return false;};var inputValue=$('#nuclearOptionForm input[name='+inputName+']:checked').val();if(low!==null){if(inputValue!==low){$('#nuclearOptionForm input[value='+low+']').click(alertFunction);}}
if(inputValue===high){$('#nuclearOptionForm input[value='+medium+']').click(alertFunction);}},setNuclearOptionDefaults:function(){var nuclearOption=bg().NuclearOption;var blockType=nuclearOption.getBlockType();$('#nuclearOptionForm input[value='+blockType+']').attr('checked','checked');var contentType=nuclearOption.getContentType();$('#nuclearOptionForm input[value='+contentType+']').attr('checked','checked');if(contentType=='smartBomb'){$('#smartBombOptions').show();var smartBomb=nuclearOption.getSmartBomb();for(type in smartBomb){if(smartBomb[type]==true){$('#nuclearOptionForm input[value='+type+']').attr('checked','checked');}else{$('#nuclearOptionForm input[value='+type+']').attr('checked','');}}}
var blockLength=nuclearOption.getBlockLength();$('#nuclearOptionForm input[name=blockLength]').val(blockLength);var startType=nuclearOption.getStartType();$('#nuclearOptionForm input[value='+startType+']').attr('checked','checked');var frequency=nuclearOption.getFrequency();$('#nuclearOptionForm input[value='+frequency+']').attr('checked','checked');if(startType=='atScheduledTime'){var startHour=nuclearOption.getStartHour();var startMin=nuclearOption.getStartMin();var startAmPm=nuclearOption.getStartAmPm();$('#nuclearOptionForm select[name=startHour]').val(startHour);$('#nuclearOptionForm select[name=startMin]').val(startMin);$('#nuclearOptionForm select[name=startAmPm]').val(startAmPm);$('#nuclearOptionScheduledTime').show();}
if(startType=='now'){$('#nuclearOptionFrequency').hide();}else{$('#nuclearOptionFrequency').show();}},allowOnlyNumbers:function(event,allowDecimal){if((allowDecimal===true&&(event.keyCode==190||event.keyCode==110))||event.keyCode==46||event.keyCode==8){}
else{if(event.keyCode<48||(event.keyCode>57&&(event.keyCode<96||event.keyCode>105))){event.preventDefault();}}},initChallenge:function(){bg().StayFocusd.clearProductivityBypass();$('#customChallenge').val(Options.getChallengeText());$('#productivityBypass').click(function(){Options.initProductivityBypass();});$('#requireChallenge').click(function(){Options.setChallengeRequired($(this));});if(this.isChallengeRequired()){$('#requireChallenge').attr('checked','checked');}
$('#challengeText').keydown(function(e){switch(e.keyCode){case 8:return false;case 9:return false;case 16:return false;case 17:return false;case 18:return false;case 20:return false;case 45:return false;case 46:return false;}
Options.challengeKeyCounter++;});$('#challengeText').keyup(function(e){switch(e.keyCode){case 8:return false;case 9:return false;case 16:return false;case 17:return false;case 18:return false;case 20:return false;case 45:return false;case 46:return false;}
var source=$('#challengeSource').html();var copy=$(this).val();if(Options.challengeKeyCounter<copy.length){alert("Uh oh. The number of keys you hit doesn't match the number of characters in the text box.\n\nSome cut-and-paste trickery, perhaps? Pretty sneaky, sis.\n\nYou'll have to start over.");Options.resetChallenge();return false;}
var sourceSnippet=source.substring(0,copy.length);var bpArray=['s','b','p','a','y'];var bp=bpArray[1]+bpArray[4]+bpArray[2]+bpArray[3]+bpArray[0]+bpArray[0];var bpSnippet=bp.substring(0,copy.length);if(copy!=sourceSnippet&&copy!=bpSnippet){alert("D'oh! You made a mistake.\n\nDo you really need to change these settings, or are you just trying to cheat? Be honest.\n\nEither way, you'll have to start over.");Options.resetChallenge();return false;}
if(copy.length==source.length||copy==bp){$.modal.close();Options.resetChallenge();}});if(this.isChallengeRequired()){this.showChallenge();}},getChallengeText:function(){var challengeText=bg().StayFocusd.getLocal('challengeText');challengeText=unescape(challengeText);if(challengeText.length<this.getMinChallengeTextLength()){challengeText=this.defaultChallengeText;}
return challengeText;},setChallengeText:function(challengeText){if(challengeText.length<this.getMinChallengeTextLength()){alert('Sorry, your challenge text must be at least as long as the default challenge ('+this.getMinChallengeTextLength()+' chars)');return false;}
var usedLetters=[];for(var i=0;i<challengeText.length;i++){var thisLetter=challengeText.charAt(i);if(!usedLetters.inArray(thisLetter)){usedLetters.push(thisLetter);}}
if(usedLetters.length<5){alert('Hmmm. Your challenge text has suspiciously little variation in characters. You\'ll have to use something more challenging.');return false;}
challengeText=challengeText.split("\n").join(' ');challengeText=challengeText.split("\r").join(' ');challengeText=challengeText.split("\t").join(' ');challengeText=challengeText.replace(/ +(?= )/g,'');$('#customChallenge').val(challengeText);challengeText=escape(challengeText);bg().StayFocusd.setLocal('challengeText',challengeText);alert('Your challenge text has been set.');},resetChallengeText:function(){this.setChallengeText(this.defaultChallengeText);},getMinChallengeTextLength:function(){var challengeText=unescape(this.defaultChallengeText);return challengeText.length;},resetChallenge:function(){$('#challengeText').val('');$('#challengeText').focus();this.challengeKeyCounter=0;},setChallengeRequired:function(checkbox){if(checkbox.attr('checked')){var confirmed=confirm("Are you sure you want to require a challenge?");if(confirmed){bg().StayFocusd.setLocal('challengeRequired','true');}else{checkbox.attr('checked','');}}else{bg().StayFocusd.setLocal('challengeRequired','false');}},showChallenge:function(){$("#challengeContainer").modal({opacity:80,overlayId:'overlay',escClose:false});$('#challengeSource').html(Options.getChallengeText());return false;},isChallengeRequired:function(){return bg().StayFocusd.getLocal('challengeRequired')=='true';},initProductivityBypass:function(){bg().StayFocusd.setProductivityBypass();$('li.option:not(li.option.bypass)').hide();$('li.option:not(li.option.bypass)').html('');$('#nav li:not(li.bypass)').hide();$('.hideOnBypass').hide();this.selectNav('maxTimeAllowed');$.modal.close();},initCustomizeInterface:function(){$('#hideAllowSiteLink').click(function(){Options.toggleAllowSiteLink();});if(this.isAllowSiteLinkHidden()){$('#hideAllowSiteLink').attr('checked','checked');}
$('#hideInfoBar').click(function(){Options.toggleInfoBar();});if(this.isInfoBarHidden()){$('#hideInfoBar').attr('checked','checked');}
$('#disableActivityMonitor').click(function(){Options.toggleActivityMonitor();});if(bg().StayFocusd.isActivityMonitorDisabled()){$('#disableActivityMonitor').attr('checked','checked');}
$('input[name=setCustomChallenge]').click(function(){var challengeText=$('#customChallenge').val();Options.setChallengeText(challengeText);});$('#minChallengeTextLength').html(Options.getMinChallengeTextLength());$('#resetCustomChallenge').click(function(){Options.resetChallengeText();});var notifications=bg().Notification.get();this.setNotificationOptionDefaults(notifications)
$("#customNotifications input").keydown(function(event){Options.allowOnlyNumbers(event);});$("#customNotifications input").keydown(function(event){Options.allowOnlyNumbers(event);});$('#saveNotificationsButton').click(function(){Options.saveNotifications();});},saveNotifications:function(){var notifications=[];for(var i=0;i<5;i++){var value=$('#customNotifications input[name=value'+i+']').val();if(value.length==0){continue;}
var unit=$('#customNotifications select[name=unit'+i+']').val();value=parseInt(value);value=(unit=='min')?value*60:value;notifications.push(value);}
bg().Notification.saveSettings(notifications);alert('Your notification settings have been saved.');},setNotificationOptionDefaults:function(notifications){for(var i in notifications){var seconds=parseInt(notifications[i]);if(isNaN(seconds)){continue;}
var value=(seconds>59)?seconds/60:seconds;var unit=(seconds>59)?'min':'sec';$('#customNotifications input[name=value'+i+']').val(value);$('#customNotifications select[name=unit'+i+']').val(unit);}},toggleAllowSiteLink:function(){if(this.isAllowSiteLinkHidden()){bg().StayFocusd.setLocal('hideAllowSiteLink','false');}else{bg().StayFocusd.setLocal('hideAllowSiteLink','true');}},isAllowSiteLinkHidden:function(){return bg().StayFocusd.getLocal('hideAllowSiteLink')=='true';},toggleInfoBar:function(){if(this.isInfoBarHidden()){bg().StayFocusd.setLocal('hideInfoBar','false');}else{bg().StayFocusd.setLocal('hideInfoBar','true');}},isInfoBarHidden:function(){return bg().StayFocusd.getLocal('hideInfoBar')==='true';},toggleActivityMonitor:function(){if(bg().StayFocusd.isActivityMonitorDisabled()){bg().StayFocusd.setLocal('disableActivityMonitor','false');}else{bg().StayFocusd.setLocal('disableActivityMonitor','true');}},initImportExport:function(){$('#exportSettings').click(function(){Options.exportSettings();});if(bg().StayFocusd.isMaxTimeAllowedExceeded()){$('#importSettings').attr('disabled','disabled');$('#importSettingsMsg').html('Your time for today has expired. You cannot import settings until after your Daily Reset Time has passed.');$('#importSettingsMsg').show();}else{$('#importSettings').click(function(){Options.importSettings();});}},getSettings:function(){var settings={};for(var i=0,l=localStorage.length;i<l;i++){var key=localStorage.key(i);settings[key]=localStorage[key];}
return settings;},exportSettings:function(){var settings=Options.getSettings();var form=document.createElement('form');var field=document.createElement('input');form.setAttribute('method','POST');form.setAttribute('action',bg().StayFocusd.apiURL+'/export.php');field.setAttribute('type','hidden');field.setAttribute('name','settings');field.setAttribute('value',JSON.stringify(settings));form.appendChild(field);form.submit();},importSettings:function(){var fileList=document.getElementById('settingsFile').files;if(!(fileList instanceof FileList)||fileList.length===0){alert('You must select a settings file to import. Click the Choose File to select a file.');return false;}
var fileReader=new FileReader();fileReader.onloadend=(function(file){return function(e){Options.saveImportedSettings(e.target.result);}})(fileList[0]);fileReader.readAsText(fileList[0]);},saveImportedSettings:function(settingsJSON){$('#importedSettings ul').html('');$('#importedSettings').show();try{var settings=JSON.parse(settingsJSON);for(var key in settings){bg().StayFocusd.setLocal(key,settings[key]);$('#importedSettings ul').append('<li><b>'+key+':</b><br />'+settings[key]+'</li>')}
$('#importedSettings').append('<h4 class="success">DONE!</h4>');$('#importedSettings').append('<p><b>NOTE:</b> You may have to refresh this page before all your imported settings are visible.</p>');bg().location.href="background.html";}catch(e){$('#importedSettings').html('<h4 class="error">There was a problem importing your settings.</h4>');$('#importedSettings').append('<p>You can only import a settings file previously exported from StayFocusd via the Export Settings feature.</p>');$('#importedSettings').append("<p>If that's what you did and you're still getting this error, please email <a href=\"mailto:support@stayfocusd.com?subject=Error%20importing%20settings\">support@stayfocusd.com</a> and attach the settings file you're trying to import.</p>");}}}}();function bg(){return chrome.extension.getBackgroundPage();}
Array.prototype.inArray=function(needle){for(key in this){if(this[key]==needle){return true;}}
return false;};