$('#back').text(getI18nMsg('back'));
$('#emptyTrash').text(getI18nMsg('clear'));
$('#loadOldNotes .button').text(getI18nMsg('loadmore'));
$('#trash').text(getI18nMsg('recycle'));
$('#option cite').text(getI18nMsg('settings'));
$('#option span').text(getI18nMsg('sonline'));
$('#SettingDone').text(getI18nMsg('done'));
$('#page-option h2').text(getI18nMsg('settings'));
$('#page-option h3:eq(0)').text(getI18nMsg('saveonline'));
$('#page-option p:eq(0)').text(getI18nMsg('saveonline_d'));
$('.loginByGoogle strong').text(getI18nMsg('newdiigo'));
$('.loginByDiigo strong').text(getI18nMsg('havediigo'));
$('input[name=username]').attr('placeholder',getI18nMsg('username_email'));
$('input[name=password]').attr('placeholder',getI18nMsg('password'));
$('.loginByDiigo span').text(getI18nMsg('signin'));
$('#page-option h3:eq(1)').text(getI18nMsg('aboutdiigo'));
$('#page-option p:eq(1)').text(getI18nMsg('aboutdiigo_d'));
$('.section:eq(1) ul li:eq(0)').text(getI18nMsg('aboutdiigo_1'));
$('.section:eq(1) ul li:eq(1)').text(getI18nMsg('aboutdiigo_2'));
$('.section:eq(1) ul li:eq(2)').text(getI18nMsg('aboutdiigo_3'));
$('.section:eq(1) ul li:eq(3)').text(getI18nMsg('aboutdiigo_4'));
$('.section:eq(1) ul li:eq(4) a').text(getI18nMsg('learnmore'));
$('#restore').text(getI18nMsg('restore'));
$('#networkError div').text(getI18nMsg('networkerror'));
$('#stopSync div').text(getI18nMsg('stopsync'));
$('#search input').attr('placeholder',getI18nMsg('search'));